export const QUERY_CONSTANT = {
    CURRENT_USER: 'current-user',
    ALL_USERS: 'all-users',
    USER: 'user',
    ALL_ORGANIZATIONS: 'all-organizations',
    ORGANIZATION: 'organization',
    ALL_PROJECTS: 'all-projects',
    PROJECT: 'project',
    ALL_POSTS: 'all-posts',
    POST: 'post',
    ALL_REQUESTS: 'all-requests',
    REQUEST: 'request',
    ALL_TAGS: 'all-tags',
    TAG: 'tag',
    ALL_TRANSFERS: 'all-transfers',
    TRANSFER: 'transfer',
    ALL_WITHDRAWALS: 'all-withdrawals',
    WITHDRAWAL: 'withdrawal',
};
